[package]
name = "chess-openings"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.203", features = ["std", "derive", "serde_derive"] }
serde_json = "1.0.119"
chess-pgn = { path = "../pgn"}
